export const ACTIONS = {
  GET_MOTOS: "GET_MOTOS",
  GET_MOTO_DETAILS: "GET_MOTO_DETAILS",
  GET_MOTOS_DATA: "GET_MOTOS_DATA",
  CHANGE_ID: "CHANGE_ID",
  MODAL: "MODAL",
  AUTH_OFFLINE: "AUTH_OFFLINE",
};

export const MOTOS_API = "http://localhost:8000/motos";


  // REACT_APP_FIREBASE_KEY = "1:887906957622:web:0c89e4c8cc06f744d7db97",
  // REACT_APP_FIREBASE_KEY = "G-W3PQJ5Q5NS"